### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by jonschlinkert** [node-base/base-generators#3]
some things for the roadmap:

- [] **base-env**: we should drop support for registering instances and only do paths and functions. If `path`, then a function should be exported. the only time an instance ought to be exported is when it's in a locally installed "config file", like a gulpfile.js
- [] **files-cache**: see https://github.com/node-base/base-generators/issues/2
- [] **configfile first**:  this is the default generator
    1. resolve the path to this file first
    1. require it in
    1. from the frame of reference of this generator:
      * try to resolve generators and tasks passed on the command line
      * try to resolve generators and tasks defined in package.json config or `*rc.json` file
    1. If generators and tasks were defined but not resolved:
      * look for generators in `node_modules`
      * look for globally installed generators
    1. Last, fall back on any built-ins (for user help, etc)
